import {
  RiMenuLine,
  RiAlertLine,
  RiLineChartLine,
  RiGroupLine,
  RiMailDownloadLine,
  RiAddCircleLine,
  RiUserVoiceLine,
  RiFileListLine,
  RiCalendarEventLine,
  RiQuestionAnswerLine,
  RiSpam2Line,
  RiFilter2Line,
  RiSearchLine,
  RiCloseLine,
  RiToolsLine,
  RiBookReadLine,
  RiBookMarkLine,
  RiMapPinLine,
  RiStore3Line,
  RiUserLine,
  RiCustomerService2Line,
  RiMacLine,
  RiStore2Line,
  RiEditBoxLine,
  RiCheckboxCircleLine,
  RiRefreshLine,
  RiFileTextLine,
  RiArrowLeftLine
} from 'react-icons/ri'

const Icons = {
  RiMenuLine,
  RiAlertLine,
  RiLineChartLine,
  RiGroupLine,
  RiMailDownloadLine,
  RiAddCircleLine,
  RiUserVoiceLine,
  RiFileListLine,
  RiCalendarEventLine,
  RiQuestionAnswerLine,
  RiSpam2Line,
  RiFilter2Line,
  RiSearchLine,
  RiCloseLine,
  RiToolsLine,
  RiBookReadLine,
  RiBookMarkLine,
  RiMapPinLine,
  RiStore3Line,
  RiUserLine,
  RiCustomerService2Line,
  RiMacLine,
  RiStore2Line,
  RiEditBoxLine,
  RiCheckboxCircleLine,
  RiRefreshLine,
  RiFileTextLine,
  RiArrowLeftLine
}

export default Icons
